name: Convert HK Bus Routes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Converter Script
        run: python -u converter.py api/transport/BusStopTime/bus_routes_google.json

      - name: Commit and Push Updated File
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/api/transport/BusStopTime/bus_routes_google.json
          git commit -m "Auto-update bus_routes_google.json" || echo "No changes to commit"
          git push
